# Generated by Django 5.1.7 on 2025-06-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='clothes')),
                ('date_purchased', models.DateField(blank=True, null=True)),
                ('thrifted', models.BooleanField()),
            ],
        ),
    ]
