# Generated by Django 5.1.7 on 2025-06-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garment',
            name='type',
            field=models.CharField(choices=[('TOP', 'Top'), ('BOTTOMS', 'Bottoms'), ('SHOES', 'Shoes'), ('ACCESSORIES', 'Accessories')], default='ACCESSORIES', max_length=20),
            preserve_default=False,
        ),
    ]
